version: '3.7'

services:
  postgres:
    image: postgres:11.8
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"  
  
  python-app:
    image: python:3.10
    container_name: python
    working_dir: /app
    volumes:
      - ./main.py:/app/main.py
    depends_on:
      - postgres
    command: ["python" , "main.py"]
  
  metabase-app:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 3000:3000
    
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgresql-data:

