version: '3.7'

services:
  postgres:
    image: postgres:11.8
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"  
  
  python-app:
    image: python:3.10
    container_name: python
    working_dir: /app
    volumes:
      - ./main.py:/app/main.py
    depends_on:
      - postgres
    command: ["python" , "main.py"]

volumes:
  postgresql-data:

